### ISSUE TITLE
Important. There are reports that students are loosing the work or kernel disconnecting in Udacity workspace

### ISSUE THREAD

**Issue by letyrodridc** [udacity/cvnd-waffle-issues#24]
Two students reported that they loose their work in the Facial Keypoints workspace. In example,

_Does the working directory refresh every few hours? I've found that my data gets deleted and my notebooks get disconnected every few hours. Is there a reason for this?_

A mentor wrote: _ I have a CVND mentee who reported all his work on the workspace disappeared after one night._

Other students are reporting frequent disconnection:
 _I gave up on the platform. I had to work on my computer. The kernel would keep disconnecting. I wrote to the support team. It was impossible to complete the assignment on the platform._

**Comment by cgearhart** [comment]
Workspace home folders are limited to approximately 5 GB. If students exceed that limit then they can become unreliable. We launched improved large file volume support today, so training data will be moved out of users home folders. However, students should be encouraged to limit the number of model checkpoints they keep, and limit the external data they store in their home folders.
