### ISSUE TITLE
Facial Keypoint Detection doesn't use GPU

### ISSUE THREAD

**Issue by letyrodridc** [udacity/cvnd-waffle-issues#9]
A student asked for the possibility to use GPU on this project. 

_Hello Leticia, on the Notebooks, do we have access to GPUs? I saw people saying they were training for hundreds of epochs. But my notebooks take forever to train on just 10 epoch with a very shallow neural net._

Is it an error not allowing GPU mode?

**Comment by cgearhart** [comment]
The facial keypoints project is intentionally CPU-only. It is possible to get good results on the project with 20-40 minutes of training.
